const express = require('express')
const router = express.Router()

// Add your routes here - above the module.exports line
require('./routes/v2/page-flow.js')(router)
// V1 work (Alpha S4)
require('./routes/v1/step-by-step.js')(router)
require('./routes/v1/notifications.js')(router)
require('./routes/v1/enforcement-selection.js')(router)
require('./routes/v1/writs.js')(router)
require('./routes/v1/dashboard.js')(router)
require('./routes/v1/govuk-pay.js')(router)
// V2 work (Alpha S5)
require('./routes/v2/step-by-step.js')(router)
require('./routes/v2/notifications.js')(router)
require('./routes/v2/enforcement-selection.js')(router)
require('./routes/v2/writs.js')(router)
require('./routes/v2/dashboard.js')(router)
require('./routes/v2/govuk-pay.js')(router)
// V3 work (Alpha S6)
require('./routes/v3/step-by-step.js')(router)
require('./routes/v3/notifications.js')(router)
require('./routes/v3/enforcement-selection.js')(router)
require('./routes/v3/writs.js')(router)
require('./routes/v3/dashboard.js')(router)
require('./routes/v3/govuk-pay.js')(router)
require('./routes/v3/cmc.js')(router)

module.exports = router
